name: Build Classes to Calendar Docker

on:
  push:
    branches:
      master
  pull_request:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Images
        run: docker-compose up --build
        env:
          TAG: latest
          FRONTEND_ENV: staging
          DOCKER_IMAGE_BACKEND: classes-to-calendar-backend
          DOCKER_IMAGE_FRONTEND: classes-to-calendar-frontend
          DOMAIN: localhost
          PROJECT_NAME: Classes to Calendar
          VERSION: "0.0.1"
          GOOGLE_CLIENT_ID: something-fake
          GOOGLE_CALENDAR_API_KEY: something-even-faker
      - name: Wait for Images to Spin Up
        run: sleep 30s
        shell: bash
      - name: List Running Docker Containers
        run: docker ps -a
