name: Build Classes to Calendar Docker

on:
  push:
    branches:
      master
  pull_request:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        run: |
          echo "DOMAIN=localhost" > .env && \
          echo "PROJECT_NAME=Classes to Calendar" >> .env && \
          echo "VERSION=0.0.1" >> .env && \
          echo "GOOGLE_CLIENT_ID=nothing" >> .env && \
          echo "GOOGLE_CALENDAR_API_KEY=nothing" >> .env
      - name: Build Docker Images
        run: docker-compose build -f docker-compose.yml
        env:
          TAG: latest
          FRONTEND_ENV: staging
          DOCKER_IMAGE_BACKEND: classes-to-calendar-backend
          DOCKER_IMAGE_FRONTEND: classes-to-calendar-frontend
          DOMAIN: localhost
      - name: Wait for Images to Spin Up
        run: sleep 30s
        shell: bash
      - name: List Running Docker Containers
        run: docker ps -a
